### PR TITLE
chore: update linting

### PR DESCRIPTION
**Pull request by XhmikosR**
🎉 Thanks for sending this pull request! 🎉

Please make sure the title is clear and descriptive.

If you are fixing a typo or documentation, please skip these instructions.

Otherwise please fill in the sections below.

**Which problem is this pull request solving?**

Example: I'm always frustrated when [...]

**List other issues or pull requests related to this problem**

Example: This fixes #5012

**Describe the solution you've chosen**

Example: I've fixed this by [...]

**Describe alternatives you've considered**

Example: Another solution would be [...]

**Checklist**

Please add a `x` inside each checkbox:

- [ ] I have read the [contribution guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have added tests (we are enforcing 100% test coverage).
- [ ] I have added documentation in the `README.md`, the `docs` directory (if
      any) and the `examples` directory (if any).
- [ ] The status checks are successful (continuous integration). Those can be
      seen below.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@ehmicky LGTY?

**Comment by ascorbic** [comment]
Hi. Thanks for the PR. Because this enables a lot of new rules it can't be merged without updating the source to pass those rules.

**Comment by XhmikosR** [comment]
@ascorbic are you sure? because I tested it and everything is green :)

**Comment by XhmikosR** [comment]
To clarify, these are already included in `@netlify/eslint-config-node` which you require (latest BTW, not a tag).

**Comment by ehmicky** [comment]
It appears that most of the rules being removed are already present in `@netlify/eslint-config-node`, with a few differences, to make it work with repositories written in pure ES modules. Since this repository does not use pure ES modules yet, this should not have an impact.

One difference though: [`func-style` is enforcing declarations](https://eslint.org/docs/rules/func-style#options) instead of expressions for functions. We probably should leave this rule as is, to leave the current function style of this repository unchanged.

**Comment by XhmikosR** [comment]
Added back `func-style` :)

**Comment by ascorbic** [comment]
It looks like the script for lint in CI is broken, which will explain why it's not giving an error! It's true func-style is the main one. I'll fix those any re-add the rule/

**Comment by XhmikosR** [comment]
I added it back already, I'll rebase this later or tomorrow morning :)

**Review by ascorbic — APPROVED** [review]

**Comment by ehmicky** [comment]
Sorry @ascorbic, it appears this actually did make much more changes than expected!

**Review by ascorbic — DISMISSED** [review]

**Comment by ascorbic** [comment]
@ehmicky A lot of it was simply that the previous script wasn;t running on most of the files. They were getting linted in VS code if we edited them, but not in CI

**Comment by XhmikosR** [comment]
Sorry about that, I didn't mean to introduce more work. I don't mind if you drop this or whatever is better for you :)

**Review by ascorbic — APPROVED** [review]

**Pull request merged**
